#!/bin/bash
 
repo="z-board"
branch="main"

echo  "  pulling from git! "
echo  "  pushing to git! "
git add .  
echo  "  i need your commit message! "
read -p "Commit message please! " desc  
echo "the commit message is $desc"
git commit -m "$desc"  
repo_url="https://${KN}:${KT}@github.com/${KN}/${repo}.git"
git push $repo_url $branch
echo  " am done with the task! good luck "
echo ""
echo ""

 

