#!/bin/bash

# Color variables
blue='\033[0;34m'
green='\033[0;32m'
clear='\033[0m'


repo="z-board"
repo_url="https://${KN}:${KT}@github.com/user/${repo}.git"
branch="main"

echo  "${blue} pulling from git!${clear}"
echo ""
echo  "${green} pushing to git!${clear}"
git add .  
echo  "${blue} i need your commit message!${clear}"
read -p "Commit message please! " desc  
echo "the commit message is $desc"
git commit -m "$desc"  
git push $repo_url $branch
echo  "${green} am done with the task! good luck${clear}"
echo ""

 

